name: D3 Front
run-name: 开始执行 Action
on: [push]
jobs:
  Build-And-Publish-D3-Box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "设置 Node 环境"
      - name: Install Node.js
        uses: actions/setup-node@v4.0.1
      - name: Install npm dependencies
        run: npm install
      - name: Init Prisma
        run: npx prisma generate
      - name: Run build task
        run: npm run build-only
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'root'
            server: '60.205.157.192'
            ssh_private_key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
            local_path: './dist/*'
            remote_path: '/usr/local/nginx/html/bili'
            sftpArgs: '-o ConnectTimeout=5'
